language: python
python:
    - "2.7"

sudo: required
cache:
    directories:
        - "~/.platformio"
        
branches:
  only:
    - master
    
addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    
before_script:
  - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
  - tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/

env:
    global:
        - USR_NAME="mhoechner"
        - USR_EMAIL="Moritz.Hoechner@infineon.com"
        - secure: soim4pr9fJQtuLG2aX9Ogx7k/nTPDPk49MW645D3NuDzWBSjaifecOdPhML7h3/WPs3QziBE7C3aTMKE7GP8/87LzCWQGi7Cg3dCkGOOkKXsOMgP1h1P4V9Vpl9EPxdz4MBFAY3hhHtojJUpMzUMN/psN7/XHzZyRw0uwqTg7ps6VLF1In2jhPUxo5F1FzR19FoxPtTyX5xcYnqCaIaG/CorwJg+Z1yNj4E0xXz5OxHcTFSKRkDixTuGDutriyKTHhds5zDVmIDkF24Og9oTjhpcgKp4T5p+MIQ8ouI7D+Xx1es3y3bnzfSK8fCRzPfP8xvAOdr61UwreGAGxwMHDivUIESMg8GBMJ2t4DmTzFtXgZ8kPSUQv7QiCrhZ8mnuk5HDgBMC03jtNHP+AldyzZyjwDiekhh3f06fTQsCUAtc3e2WinwLkCt+i3XE6iAIY5cgOJWMHlfn1bxzS9i19TArdVeGfQufA5ZG8runhYzgQP2C8jZ1Dwn6pKuHjTHM/rMyDX3qJ2ngS1+PCcHqa7TxpI3zq0/aG5GoMyaT3vM9ZHI1RF69oYsPusZcfJ3b7mJfC/O42ViqRXx6WFX/sQZQNPsWnKbdp0xaNa2iqi+/FcO8027Zq33I0EkQK4c2ZXWwqw6NHqSN94zea//a6WnO4ArLxQ2xqT5xEqdViHY=
    matrix:
        - PLATFORMIO_CI_SRC=examples/Cartesian 
        - PLATFORMIO_CI_SRC=examples/Cartesian_low_power 
        - PLATFORMIO_CI_SRC=examples/sine_generator 

install:
    ## build with stable core
    # - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    # - pip install -U platformio
    # - platformio platform install -f file:///tmp/builder/. 

    # build with development version
    - git clone https://github.com/Infineon/XMC-for-Arduino.git /tmp/core
    - zip -r /tmp/core/framework-arduinoxmc.zip /tmp/core/arm  
    - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    - cd /tmp/builder
    - platform_json=$(<platform.json)
    - rm platform.json
    - jq '.packages."framework-arduinoxmc".version = "file:///tmp/core/framework-arduinoxmc.zip"' <<<"$platform_json" > platform.json
    - pip install -U platformio
    - platformio platform install -f file://. 
    - cd -
script:
    - platformio ci --lib="." --board=xmc1100_xmc2go

after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/well-automated-documentation.git
        cd well-automated-documentation/docs
        # cd $TRAVIS_BUILD_DIR/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi
