language: python
python:
    - "2.7"

sudo: required
cache:
    directories:
        - "~/.platformio"
        
branches:
  only:
    - master
    
addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    
before_script:
  - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
  - tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/

env:
    global:
        - USR_NAME="Sun Yuxi (IFAG DES SDF FW)"
        - USR_EMAIL="Yuxi.Sun@infineon.com"
        - secure: OVy8b8wt07Clr1RXXsF4j+KZGzl/e7Yh8ybrXHu65y/r03rqqtLHvIekhAd3wshGyctWR7mllkW0NHhz22PDP9q7RxguArLxSfZHMUoPv9CyqfTj/oU8WRWP2juQRsrMTEYVbgI3yEGdsfuoQitMSEz7FIwi9wKe/v51c89QEISsVFB6HGavutXdK8HRT5lpmSgpU2ljsOtgitznQKQ7+uO7VNWw9e+mAjwI2Vr7A79Itly7K/942e6nWMsW+CYo+4ZTcY2tB2z7rJcY1RsYWfBNecUuPWFVeooCqLbPFLVxo4Zq0npXX4Eh0BBd+4K/A1H35f6Pzq1DqdBwMlZgs+AKSytdBVWXSDZ2uj6cYevXeymwkVjmrZsxshGDrIEl2BzFF7iBNNxhfZlmd4kD3u9z+8mswZgIrME0rQ0asGAXnr9l84rMQCpc4CrVeoqsMGL+0VisG+4ZNM4tcsHfBHLn8zcTyu+Q7/ZcdN0tfwodMBEMgZMv6vheudt2WK+zQNZ2skrwaLlHmOaQLWmO2pfnajDa22IgoZCF1T6TxSgykBvnl7HKN82Y23Ybq4OcQFk3W6AUiNjo76iG7MdaYWsKHYYgcG//lkvH/im9vEMNFy+jn4hbCjqObTQUYpk3gJDqRAwpj1p90VA2mrxFxnEeaAB+QFwA8o4e40CNhYk=
    matrix:
        - PLATFORMIO_CI_SRC=examples/Cartesian 
        - PLATFORMIO_CI_SRC=examples/Cartesian_low_power 
        - PLATFORMIO_CI_SRC=examples/sine_generator 

install:
    ## build with stable core
    # - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    # - pip install -U platformio
    # - platformio platform install -f file:///tmp/builder/. --without-package=uploader

    # build with development version
    - git clone https://github.com/Infineon/XMC-for-Arduino.git /tmp/core
    - zip -r /tmp/core/framework-arduinoxmc.zip /tmp/core/arm  
    - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    - cd /tmp/builder
    - platform_json=$(<platform.json)
    - rm platform.json
    - jq '.packages."framework-arduinoxmc".version = "file:///tmp/core/framework-arduinoxmc.zip"' <<<"$platform_json" > platform.json
    - pip install -U platformio
    - platformio platform install -f file://. --without-package=uploader
    - cd -
script:
    - platformio ci --lib="." --board=xmc1100_xmc2go

after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/well-automated-documentation.git
        cd well-automated-documentation/docs
        # cd $TRAVIS_BUILD_DIR/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi