language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    - doxygen
    - graphviz
    
before_script:
  - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
  - tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/

env:
    - PLATFORMIO_CI_SRC=examples/Cartesian 
    - PLATFORMIO_CI_SRC=examples/Cartesian_low_power 
    - PLATFORMIO_CI_SRC=examples/sine_generator 

install:
    ## build with stable core
    # - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    # - pip install -U platformio
    # - platformio platform install -f file:///tmp/builder/. --without-package=uploader

    # build with development version
    - git clone https://github.com/Infineon/XMC-for-Arduino.git /tmp/core
    - zip -r /tmp/core/framework-arduinoxmc.zip /tmp/core/arm  
    - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    - cd /tmp/builder
    - platform_json=$(<platform.json)
    - rm platform.json
    - jq '.packages."framework-arduinoxmc".version = "file:///tmp/core/framework-arduinoxmc.zip"' <<<"$platform_json" > platform.json
    - pip install -U platformio
    - platformio platform install -f file://. --without-package=uploader
    - cd -
script:
    - platformio ci --lib="." --board=xmc1100_xmc2go

#after_success: